Feature cn 107 prevent data loss
unfoldingWord/gateway-translate pull request #132
Opened 2023-01-18 14:04 UTC by mandolyte

# Describe what your pull request addresses

- [ ] Work in progress -- do not review

## Test Instructions

- [ ]

2023-01-20 18:05 UTC, superdav42 requested changes
Small change requested but it does not address all the requirements of the issue #107.
> Now close that tab or refresh the page

We need to show the same or similar warning when the users tries to close the tab with unsaved changes. The react hook `useBeforeUnload` should help tccreate does this with it https://github.com/unfoldingWord/tc-create-app/blob/c625b93417fe351ef08252a3c846386e09712553/src/Layout.js#L46

2023-01-22 13:51 UTC, mandolyte commented on src/components/ScriptureWorkspace.js
> +import { SetMeal } from '@mui/icons-material'
fixed

2023-01-22 13:53 UTC, mandolyte commented
The updates address the tab closing, but closing the entire browser seems to work differently. I updated the test instructions. Let me know what you think.

I got the Nextjs example and pretty much pasted it into `/pages/_app.js`. I commented out the parts I did not think we needed, but left them there since the other conditions handled might prove useful.

2023-02-06 21:54 UTC, superdav42 requested changes
> Click to close the browser, a warning message is shown -- however, the app appears to be reset. Data may be lost?

It didn't work this way for me. Closing the app did the same thing as closing the tab. Nothing was loss

Remove the changes in Layout.js and I think this is golden.

2023-02-06 21:54 UTC, superdav42 commented on src/components/Layout.js
> +
Removed this unused code. Looks like it's in _app.js
```suggestion
```

2023-02-06 21:54 UTC, superdav42 commented on src/components/Layout.js
> +// import { useBeforeunload } from 'react-beforeunload';
```suggestion
```

2023-02-06 21:54 UTC, superdav42 commented on src/components/Layout.js
> +
```suggestion
```

2023-02-07 16:36 UTC, merged