re-fix. but upload may still need work
unfoldingWord/gateway-translate pull request #96
Opened 2022-12-03 14:30 UTC by mandolyte

# Describe what your pull request addresses

- [ ] Trying again to fix edit-ability rules

## Test Instructions

- [ ] open a file belonging to default org/lang: should be editable
- [ ] open a file outside default org/lang: should not be editable
- [ ] open a file by URL: should not be editable
- [ ] open a file by uploading: since this works by downloading, it doesn't update the original local file. So perhaps this should be a non editable case too

Also note that the user can easily click the pencil icon and save changes to local storage.

2022-12-05 15:56 UTC, superdav42 requested changes
I'm afraid it doesn't work.  Opening a file belonging to default org/lang: is NOT editable. Every source opens with editable off.

2022-12-06 16:20 UTC, mandolyte commented
Running locally with es-419_gl as org and es-419 as lang set in account settings page.
- org es-419_gl and lang es-419: book Titus is editable
- org uW and en_ust and Titus is *not* editable (change to uW made in dialog)
- used custom URL https://qa.door43.org/translate_test/es-419_gstx/src/branch/master/57-TIT.usfm: is *not* editable
- uploaded a file from local: is *not* editable

2022-12-06 17:32 UTC, larsgson reviewed
LGTM.
What were the changes? Was this fixed simply by merging from latest main? 
(I was a bit surprised by not finding hardly any changed files)

2022-12-06 17:37 UTC, superdav42 approved these changes

2022-12-06 21:41 UTC, merged